import os
import numpy as np 
import matplotlib.pyplot as plt
import imageio
from tqdm import tqdm


def load_steps(filename):  
    """
    Loads the heat values from the txt file generated by the C++ simulation

    Inputs:
        filename (str): Path to the text file to be read.

    Outputs:
        steps (list of int): A list of extracted step numbers.
        values (numpy.ndarray): A 2D array containing the temperatur of all the points.
    """
    steps = []
    values = []

    with open(filename, 'r') as f:
        for line in f:
            if line.startswith("Step:"):
                steps.append(int(line.split()[1]))
            else:
                try:
                    nums = [float(x) for x in line.split()]
                    if nums:
                        values.append(nums)
                except ValueError:
                    pass

    return steps, np.array(values)


def create_gif(
        values: np.ndarray, 
        output: str, 
        delete_temps: bool
        ):
    """
    Creates a GIF visualizing temperature evolution using colored squares.
    Works for current 1D arrays and is prepared for future 2D fields.

    Inputs:
        values (array): shape (steps, N) for 1D data; later also (steps, H, W) for 2D data
        output (str): path to output GIF file
        delete_temps (bool): If True, all temporary PNG frames are deleted after the GIF is created.

    Output:
        A GIF showing the temperature distribution over time as a heatmap.
    """

    images = []
    vmin = np.min(values)
    vmax = np.max(values)

    for i, arr in enumerate(tqdm(values, desc="Rendering frames")):

        # if 1D
        if arr.ndim == 1:
            arr_2d = arr.reshape(1, -1)
        else:
            arr_2d = arr  # for 2D later

        plt.figure(figsize=(6, 4))
        plt.imshow(arr_2d, cmap="coolwarm", vmin=vmin, vmax=vmax, aspect="auto")
        plt.colorbar(label="Temperature")
        plt.title(f"Temperature Field - Step {i}")
        plt.xlabel("Position")
        if arr.ndim == 1:
            plt.ylabel("1D Heat Field")
        else:
            plt.ylabel("Y")

        filename = f"temp/_frame_{i}.png"
        plt.savefig(filename)
        plt.close()

        images.append(imageio.imread(filename))

    imageio.mimsave(output, images, duration=0.4)
    print(f"GIF saved as: {output}")

    if delete_temps:
        for i in range(len(values)):
            try:
                os.remove(f"temp/_frame_{i}.png")
            except FileNotFoundError:
                pass
        print("Finished deleting temporary plots.")



if __name__ == "__main__":
    steps, values = load_steps("../outputs/raw/simulation_1D.txt")
    create_gif(
        values,
        output="../outputs/plots/heat_1D_2.gif",
        delete_temps=True)